name: ProjectXANA
version: 0.1
author: Sky, GoodOldJack12
main: pro.mrcl.ProjectXANA.XANAMain
depend: [ProjectCarthage]
load: POSTWORLD
website: www.mrcl.pro
api-version: 1.12
commands:
  possess:
    description: Sets the target under the control of XANA
    permission: ProjectXANA.possess